services:
  - type: web
    name: marco-boutique
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marco-db
          property: connectionString

databases:
  - name: marco-db
    databaseName: marco
    user: marco
    plan: free 
