services:
  - type: web
    name: marco-boutique
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn wsgi:application --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marco-db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src

databases:
  - name: marco-db
    databaseName: marco
    user: marco
    plan: free 
