"""Add image_filename to Boutique model

Revision ID: 014ac42b202f
Revises: 52503cfd1ac2
Create Date: 2025-05-18 02:27:39.379242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014ac42b202f'
down_revision = '52503cfd1ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boutiques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boutiques', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
