"""Add address column to boutiques table

Revision ID: 52503cfd1ac2
Revises: 5032cd097f12
Create Date: 2025-05-18 01:54:06.229932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52503cfd1ac2'
down_revision = '5032cd097f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boutiques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boutiques', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
