"""Add target_audience to Boutique model

Revision ID: 926f7461df8c
Revises: 014ac42b202f
Create Date: 2025-05-18 19:21:24.283986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926f7461df8c'
down_revision = '014ac42b202f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boutiques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_audience', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boutiques', schema=None) as batch_op:
        batch_op.drop_column('target_audience')

    # ### end Alembic commands ###
