"""Ajout des champs de modération utilisateur

Revision ID: bf4b9bcf46ed
Revises: 841653c51f56
Create Date: 2025-05-18 23:17:29.066847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4b9bcf46ed'
down_revision = '841653c51f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ban_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ban_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('warning_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_warning', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('moderation_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('moderation_notes')
        batch_op.drop_column('last_warning')
        batch_op.drop_column('warning_count')
        batch_op.drop_column('ban_date')
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
